services:
  - type: web
    name: cirkle-commission-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --prefix discord-bot
    startCommand: npm start --prefix discord-bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
