services:
  - type: web
    name: cirkle-commission-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd discord-bot && npm install
    startCommand: cd discord-bot && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
