name = "timeclock-backend"
main = "worker.js"
compatibility_date = "2025-01-09"

# KV Namespaces for data storage
[[kv_namespaces]]
binding = "DATA"
id = "af9db3ed58534d12b8faca9bf294ae44"

[triggers]
crons = ["*/5 * * * *"]
